-- Keep the published Sicilian detail pages as rich as the catalog source.
-- The update is keyed by slug and preserves publication status and forecast data.

with catalog_content (slug, description, services, facts) as (
  values
    ('san-vito-lo-capo', 'Una grande spiaggia di sabbia chiara nel golfo di San Vito Lo Capo, ai piedi di Monte Monaco. L''arenile urbano unisce acqua bassa, accessi comodi e servizi stagionali.', array['servizi stagionali']::text[], array['Suolo — Sabbia chiara e fine lungo l''arenile urbano', 'Fondale — Basso e digradante vicino alla riva', 'Esposizione — Nord-ovest, nella baia tra Monte Monaco e Punta del Solanto', 'Servizi — Tratti attrezzati stagionali, stabilimenti e servizi sul lungomare', 'Accesso — Facile, ingresso dalla zona urbana e dal lungomare', 'Ambiente — Grande baia urbana ai piedi di Monte Monaco e del borgo marinaro']::text[]),
    ('baia-santa-margherita-macari', 'Una baia panoramica tra Castelluzzo e Macari, con sabbia e tratti ghiaiosi affacciati sul golfo. È un punto tranquillo per mare e passeggiate, ma servizi e accessi possono variare in stagione.', array['parcheggi stagionali']::text[], array['Suolo — Sabbia e tratti ghiaiosi lungo la baia', 'Fondale — Digrada verso il largo; profondità da verificare nel tratto scelto', 'Esposizione — Nord-ovest, affaccio aperto sul golfo', 'Servizi — Nessun servizio stabile verificato; disponibilità stagionale da controllare', 'Accesso — Facile dalla viabilità locale; parcheggi e accessi possono variare', 'Ambiente — Baia panoramica tra Castelluzzo e Macari, con costa naturale']::text[]),
    ('cala-tonnarella-dell-uzzo', 'Una caletta della Riserva dello Zingaro incastonata tra ciottoli chiari, roccia e acqua trasparente. Si raggiunge a piedi lungo i sentieri della Riserva, senza servizi di spiaggia.', array[]::text[], array['Suolo — Ciottoli bianchi levigati e roccia calcarea', 'Fondale — Fondo roccioso e ciottoloso, con acqua molto trasparente', 'Esposizione — Nord-ovest, versante nord della Riserva', 'Servizi — Nessun servizio di spiaggia stabile; verificare regole e punti acqua della Riserva', 'Accesso — Sentiero della Riserva, dal versante nord e solo a piedi', 'Ambiente — Riserva dello Zingaro, macchia mediterranea e calette selvagge']::text[]),
    ('cala-marinella-zingaro', 'Una piccola caletta selvaggia della Riserva dello Zingaro, tra ciottoli, pareti rocciose e macchia mediterranea. La visita richiede un percorso a piedi e una preparazione autonoma.', array[]::text[], array['Suolo — Ciottoli chiari e roccia lungo la caletta', 'Fondale — Fondo roccioso e ciottoloso, da esplorare con cautela', 'Esposizione — Nord-ovest, lungo il sentiero costiero', 'Servizi — Nessun servizio stabile verificato; portare acqua e necessario', 'Accesso — Sentiero costiero della Riserva, raggiungibile a piedi', 'Ambiente — Costa selvaggia della Riserva e macchia mediterranea']::text[]),
    ('cala-capreria-zingaro', 'La prima caletta del versante di Scopello nella Riserva dello Zingaro, con ciottoli chiari, scogli e mare limpido. L''accesso è legato al sentiero costiero e richiede calzature adatte.', array[]::text[], array['Suolo — Ciottoli bianchi levigati e rocce affioranti', 'Fondale — Roccioso e ciottoloso, adatto alla maschera con mare calmo', 'Esposizione — Nord-ovest, versante di Scopello', 'Servizi — Nessun servizio stabile verificato nella caletta', 'Accesso — Sentiero dall''ingresso sud della Riserva; calzature adatte', 'Ambiente — Pareti rocciose, macchia mediterranea e costa protetta']::text[]),
    ('tonnara-di-scopello', 'Uno specchio d''acqua tra i faraglioni e l''antica tonnara di Scopello, più luogo costiero che spiaggia tradizionale. L''ingresso balneare e i servizi dipendono dalle regole della struttura.', array[]::text[], array['Suolo — Roccia e piattaforme naturali tra i faraglioni', 'Fondale — Acqua limpida e fondo roccioso, profondo in alcuni punti', 'Esposizione — Nord-ovest, costa di Scopello', 'Servizi — Modalità di ingresso e servizi dipendono dalla struttura; verificare prima', 'Accesso — Accesso regolamentato e non tradizionale; verificare disponibilità', 'Ambiente — Tonnara storica, faraglioni e paesaggio costiero di Scopello']::text[]),
    ('guidaloca', 'Una baia ampia di ghiaia bianca e ciottoli, con acqua cristallina e una parte rocciosa ideale per esplorare con la maschera. È riparata e offre anche lido e servizi stagionali.', array['lido', 'servizi stagionali']::text[], array['Suolo — Ghiaia bianca e ciottoli; tratti rocciosi a levante', 'Fondale — Basso e digradante in una baia riparata', 'Esposizione — Nord, con conca riparata dai venti', 'Servizi — Lido, lettini, ombrelloni e snack stagionali', 'Accesso — Facile, dalla strada per Scopello', 'Ambiente — Baia ampia tra Punta Gran Marinaro e Puntazza']::text[]),
    ('cala-rossa-favignana', 'Una baia spettacolare di Favignana tra scogli piatti, calcarenite e acqua trasparente. La discesa è impegnativa e l''area non offre la comodità di un lido tradizionale.', array[]::text[], array['Suolo — Scogli piatti di calcarenite e tratti di sabbia chiara', 'Fondale — Roccioso, con accessi e profondità variabili', 'Esposizione — Nord-est, sulla costa nord-orientale di Favignana', 'Servizi — Nessun servizio stabile direttamente sulla cala', 'Accesso — Discesa lunga e rocciosa; scarpe adatte consigliate', 'Ambiente — Baia di calcarenite e cave di tufo, senza lido attrezzato']::text[]),
    ('cala-azzurra-favignana', 'Una baia del versante sud-est di Favignana con sabbia chiara, riflessi rosati e acqua azzurra. Il fondale basso e la protezione dai venti la rendono una delle cale più semplici per un bagno tranquillo.', array['bar']::text[], array['Suolo — Sabbia bianca con riflessi rosati', 'Fondale — Basso e sabbioso, con acqua generalmente calma e limpida', 'Esposizione — Sud-est, sul versante meridionale di Favignana', 'Servizi — Bar vicino alla discesa; eventuali aree attrezzate da verificare', 'Accesso — Facile, sentiero dalla strada e secondo accesso laterale', 'Ambiente — Baia riparata da venti e correnti, con panorama verso Marsala']::text[]),
    ('lido-burrone-favignana', 'La grande spiaggia sabbiosa di Favignana, con ingresso dolce e acqua bassa. È la scelta più comoda dell''isola per famiglie e servizi: stabilimento, lettini, bar e ristorante.', array['lido', 'bar', 'ristorante', 'servizi stagionali']::text[], array['Suolo — Sabbia fine e chiara', 'Fondale — Basso e sicuro, con ingresso dolce in acqua', 'Esposizione — Sud-ovest, sul versante meridionale di Favignana', 'Servizi — Stabilimento, lettini, ombrelloni, bar e ristorante', 'Accesso — Facile, strada asfaltata dalla zona abitata', 'Ambiente — Ampia baia sabbiosa, comoda per famiglie e nuoto tranquillo']::text[]),
    ('mondello', 'La grande spiaggia di Palermo tra Monte Pellegrino e Monte Gallo, con sabbia chiara e fondale che degrada lentamente. È urbana e molto servita, con lido, spiaggia libera e collegamenti dal centro.', array['lidi', 'servizi stagionali']::text[], array['Suolo — Sabbia chiara e fine', 'Fondale — Basso e digradante verso il largo', 'Esposizione — Nord, nel golfo tra Monte Pellegrino e Monte Gallo', 'Servizi — Spiaggia libera, lidi e servizi accessibili stagionali', 'Accesso — Facile, dal lungomare urbano e con collegamenti da Palermo', 'Ambiente — Borgo marinaro, Parco della Favorita e ville Liberty']::text[]),
    ('barcarello-sferracavallo', 'Un tratto roccioso di Sferracavallo tra Capo Gallo e Isola delle Femmine, scelto per acqua limpida, snorkeling e tramonti. Non è una spiaggia sabbiosa e l''accesso va valutato sul posto.', array[]::text[], array['Suolo — Scogli e piattaforme rocciose', 'Fondale — Roccioso, da esplorare con cautela', 'Esposizione — Nord-ovest, sulla costa di Sferracavallo', 'Servizi — Nessun servizio di spiaggia verificato; servizi di borgata da controllare', 'Accesso — Dal lungomare, con tratti rocciosi e percorso da verificare', 'Ambiente — Costa tra Capo Gallo e Isola delle Femmine, aperta ai tramonti']::text[]),
    ('isola-delle-femmine', 'Un litorale urbano affacciato sull''Area Marina Protetta Capo Gallo–Isola delle Femmine, con più accessi e tratti diversi. La composizione del fondo e i servizi cambiano lungo la costa.', array[]::text[], array['Suolo — Sabbia e tratti misti lungo il litorale', 'Fondale — Digrada in alcuni tratti; profondità variabile tra gli accessi', 'Esposizione — Nord, con l''isolotto davanti alla costa', 'Servizi — Spiaggia libera e servizi stagionali da verificare', 'Accesso — Facile, con più accessi dal litorale urbano', 'Ambiente — Area marina protetta Capo Gallo–Isola delle Femmine']::text[]),
    ('capaci', 'Un lungo litorale sabbioso vicino Palermo, con acqua bassa e accessi adatti a una giornata semplice. In stagione si alternano spiaggia libera, stabilimenti e servizi da verificare.', array['lidi', 'servizi stagionali']::text[], array['Suolo — Sabbia fine e chiara', 'Fondale — Basso e digradante, adatto alla balneazione familiare', 'Esposizione — Nord, sul litorale aperto di Capaci', 'Servizi — Stabilimenti e servizi stagionali; disponibilità da verificare', 'Accesso — Facile, con accessi dalla zona urbana', 'Ambiente — Ampio litorale sabbioso tra Palermo e il golfo di Carini']::text[]),
    ('cala-rossa-terrasini', 'Una cala di Terrasini dominata da scogliere rossastre e acqua limpida, ideale per tuffi e snorkeling. Non è una spiaggia di sabbia: servono prudenza, scarpe da scoglio e autonomia.', array[]::text[], array['Suolo — Scogliera rossastra e piattaforme rocciose', 'Fondale — Limpido e roccioso, interessante per lo snorkeling', 'Esposizione — Ovest-nord-ovest, sulla costa di Terrasini', 'Servizi — Nessun servizio di spiaggia stabile verificato; portare acqua', 'Accesso — Moderato, con ultimi tratti a piedi e movimento sugli scogli', 'Ambiente — Costa di Terrasini tra Cala Rossa e Capo Rama']::text[]),
    ('la-praiola-terrasini', 'Una piccola cala urbana di Terrasini con battigia di pietre vulcaniche scure e atmosfera tranquilla. L''accesso è solo da scale, senza rampa, e i servizi di spiaggia non sono verificati.', array[]::text[], array['Suolo — Pietre vulcaniche scure e tratti rocciosi', 'Fondale — Roccioso; ingresso in acqua da valutare sul posto', 'Esposizione — Nord-ovest, sul lungomare di Terrasini', 'Servizi — Nessun servizio stabile verificato nella caletta', 'Accesso — Ingresso solo da scale; nessuna rampa disponibile', 'Ambiente — Piccola cala urbana dall''atmosfera tranquilla']::text[]),
    ('magaggiari-cinisi', 'Un ampio litorale sabbioso di Cinisi, con acqua dai toni turchesi e un affaccio aperto verso il tramonto. È vicino all''abitato, mentre servizi e attività possono cambiare con la stagione.', array['servizi stagionali']::text[], array['Suolo — Sabbia fine e chiara', 'Fondale — Digrada verso il largo; condizioni variabili con il vento', 'Esposizione — Nord, nella baia di Cinisi', 'Servizi — Servizi stagionali e attività sportive da verificare', 'Accesso — Facile, litorale vicino all''abitato', 'Ambiente — Baia aperta con tramonti verso il golfo di Castellammare']::text[]),
    ('spiaggia-del-lungomare-cefalu', 'La spiaggia urbana di Cefalù, un lungo arenile di sabbia dorata ai piedi della Rocca e del centro storico. Il fondale digrada dolcemente e il lungomare concentra accessi, lidi e servizi stagionali.', array['lidi', 'servizi stagionali']::text[], array['Suolo — Sabbia dorata e fine', 'Fondale — Digrada dolcemente verso il largo', 'Esposizione — Nord-nord-est, davanti al centro storico', 'Servizi — Stabilimenti e attrezzature stagionali lungo il litorale', 'Accesso — Facile, con accessi urbani dal Lungomare Giardina', 'Ambiente — Lungomare ai piedi della Rocca, con vista su porto e Duomo']::text[]),
    ('caldura-cefalu', 'Una piccola cala di Cefalù tra ghiaia, ciottoli e scogli, più appartata rispetto al lido del centro. L''accesso con scale e il fondale profondo vicino alla riva la rendono più adatta a chi cerca un ambiente roccioso.', array[]::text[], array['Suolo — Ghiaia, ciottoli e scogli affioranti', 'Fondale — Profondo vicino alla riva, con fondo roccioso', 'Esposizione — Est-nord-est, nell''area di Caldura', 'Servizi — Nessun lido stabile verificato; portare acqua e attrezzatura', 'Accesso — Moderato, discesa e scale dalla zona di Via Cavallaro', 'Ambiente — Piccola cala riservata tra verde, rocce e mare aperto']::text[]),
    ('mazzaforno-cefalu', 'Una contrada costiera con più calette di Cefalù, dove sabbia, sassolini, ciottoli e rocce si alternano tra gli accessi. Non è un unico arenile: servizi, concessioni e difficoltà cambiano da un tratto all''altro.', array[]::text[], array['Suolo — Tratti di sabbia, sassolini, ciottoli e rocce frastagliate', 'Fondale — Variabile tra le baie; verificare il singolo accesso', 'Esposizione — Nord-nord-est, sulla contrada Mazzaforno', 'Servizi — Servizi e concessioni da verificare nei singoli accessi', 'Accesso — Moderato, con più scale e sentieri verso le calette', 'Ambiente — Contrada costiera a circa 3 km da Cefalù, con baie multiple']::text[]),
    ('balestrate', 'Un lungo litorale di sabbia fine sul golfo di Castellammare, con fondale basso e accessi semplici dalla zona abitata. Alle spalle del litorale restano aree verdi e boschive; servizi e concessioni sono stagionali.', array['servizi stagionali']::text[], array['Suolo — Sabbia fine e chiara', 'Fondale — Basso e digradante, adatto alle famiglie', 'Esposizione — Nord, affacciata sul golfo di Castellammare', 'Servizi — Spiaggia libera e stabilimenti stagionali', 'Accesso — Facile, dalla zona abitata e dalla viabilità locale', 'Ambiente — Litorale ampio con bosco e vegetazione nella fascia retrostante']::text[])
)
update public.beaches as beach
set
  description = catalog_content.description,
  services = catalog_content.services,
  facts = catalog_content.facts,
  updated_at = now()
from catalog_content
where beach.slug = catalog_content.slug
  and beach.is_published = true
  and beach.publication_status in ('verified', 'stale');

do $$
declare
  complete_count integer;
begin
  select count(*)
  into complete_count
  from public.beaches
  where is_published = true
    and publication_status in ('verified', 'stale')
    and array_length(facts, 1) = 6;

  if complete_count <> 21 then
    raise exception 'Expected 21 published beaches with six facts, found %', complete_count;
  end if;
end
$$;
;
